### ISSUE TITLE
Environment creation fails if home folder is not writable

### ISSUE THREAD

**Issue by lisakmalins** [kramundson/snakemake_chrom_dosage#1]
When creating the conda environment, I got an error that I don't have write permission in my home folder on the Comai Lab server.

```
$ conda env create --name dosage -f environment.yaml
Collecting package metadata: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /home/lmalins/.conda/pkgs/urls.txt
```

I fixed it by editing my conda configuration to use the directory `/scratch/lmalins` where I do have write permission:

```
conda config --show 	# show current configuration
conda config --add envs_dirs /scratch/lmalins/.conda/envs
conda config --add pkgs_dirs /scratch/lmalins/.conda/pkgs
```

I recommend you add this workaround to the README for users with similar write restrictions.

**Comment by kramundson** [comment]
Thanks, done.
